UQComputingSociety/uqcsbot-discord

uqcsbot/channels.py

This makes !joinchannels redundant but keeps it as a hidden alias just in case.

Change !joinchannel to support multiple channels.

---

uqcsbot/advent.py

Forgot to add timezone information to the schedule task for advent

Forgot to add timezone information to cron

---

uqcsbot/__main__.py
uqcsbot/error_handler.py

Sends a message if a required positional argument is missing. All errors also get logged

Add a basic error handler

---

uqcsbot/text.py

Added scary text

---

uqcsbot/yelling.py

Certainly not exhaustive, please add if there's more you know of - this at least should cover most common use cases

#YELLING Regex Updates

---

.github/workflows/main.yml

I'm attempting to fix this no deploy issue

Remove docker tags, use git sha

---

uqcsbot/channels.py

I'm not really sure how to test whether my code works. Hopefully this removes the the hash before a channel name such that it can be dealt with normally. In response to #29

allowed !joinchannel to asccept names leading with hashes

---

poetry.lock
pyproject.toml
uqcsbot/channels.py
uqcsbot/models.py

This adds an epic™ new way of joining/leaving channels by reacting to a uqcsbot message. The message updates itself automatically when new channels are made joinable, and users are DM'd when they join or leave. It should help reduce some of the spam in the `#bot-testing` channel.
This time around I used a lot of the pre-existing infra to store the reactions and the message ID. Let me know what y'all think, I'm open to any suggestions.

react-joins #2

---

uqcsbot/text.py

Please accept I promise I am a changed man.

Removed The Disciplinary Function

---

uqcsbot/whatweekisit.py

Merging in the new discord.py 2 code missed this cog, and therefore wasn't out of the box compatible. This was picked up at runtime, not build time

Migrate whatweekisit to new system

---

uqcsbot/haiku.py

add quick syllable-check command to ~~stop 17-word haiku attempts~~ make 17-word haiku attempts not the only way to test stuff

add syllable-check command

---

tests/test_haiku.py
uqcsbot/haiku.py

Fixed some bugs relating to how a final "s" is interpreted. Added test cases (now all passed) for the mis-examples shown in #bot-testing.

Improved Haiku: syllable detection

---

uqcsbot/__main__.py
uqcsbot/cowsay.py

Had a weird thought, "what if `cowsay` was in discord?" Then I accidentally built that instead of doing any work.
The command is `/cowsay message`
```
_____________ 
< hello world >
------------- 
\   ^__^
\  (oo)\_______
(__)\       )\/\ 
||----w |
||     ||
```
There are also optional arguments:
- `tongue` which will allow the cow to stick out its tongue
- `tux` which changes the cow to the Linux Tux
- `mood` which will change the eyes from a select list:
```py
select_list = dict(
Normal = 'oo',
Borg = '==',
Dead = 'xx',
Greed = '$$',
Paranoid = '@@',
Stoned = '**',
Tired = '--',
Wired = 'OO',
Youthful = '..'
)
```

Added Cowsay

---

tests/test_haiku.py
uqcsbot/haiku.py

Added better determination of syllables in words ending in "ate", alongside relevant tests and a few more exceptions that do not fit into any large groups.
Slight code organisation changes to "le" ending words as well.

Haiku: Better distinction of words ending in "ate"

---

uqcsbot/__main__.py
uqcsbot/snailrace.py
uqcsbot/utils/snailrace_utils.py

As I perused the channels of the UQCS Discord server, I sensed a certain somberness in the atmosphere, as though `cowsay` no longer brings on any excitement. Determined to shake things up and contribute to the community, I took it upon myself to introduce a new feature to the server's bot.
I struggled to come up with a fresh and exciting idea, but inspiration finally struck me while racing my father-in-law home from a long weekend of manual labor in far-off regional Victoria. The idea of Snail Racing popped into my head like a bolt of lightning - a thrilling, fun, and unique addition to the UQCS bot's arsenal.
```
1 |.......🐌       | coxy
2 |..............🐌| JimmyD 🏁
3 |......🐌        | Jason
4 |.......     🐌  | Danie
5 |...........🐌   | Brandon
6 |.............🐌 | Tom
```
This was also …

Snail Racing?

---

uqcsbot/starboard.py

the miracle of testing in prod

switch queries to and_

---

uqcsbot/holidays.py
uqcsbot/yelling.py

That's right, we're coming for you. This should now detect if anyone edits their message, but only if they now contain lowercase.
Also, bug fix for daily holiday message not being in the Brisbane timezone

Detect if edits are made in #yelling

---

README.md

As a newcomer, I always found these instructions useful, so I thought it would be good to add. Feel free to reword.

Add Pyright instructions to the readme

---

uqcsbot/dominos_coupons.py

The embed would show an empty "Keywords: " line even if there were no keywords given. Also italicized the keywords (if given).

Dominos: Neatened embed

---

tests/test_haiku.py
uqcsbot/static/syllable_rules.yaml

As said on the tin. Bug found by TheOnlyMrCat [here](https://discord.com/channels/813324385179271168/836243768411160606/1132261136406941716).

Haiku: Fixed syllable count for "poem"

---

uqcsbot/haiku.py

I was silly and left in a debugging print statement. This commit fixes that.

Removed erronious print statement

---

uqcsbot/models.py
uqcsbot/yelling.py

With this change, when somebody fails to yell in yelling they'll be timed out for 15 seconds. If they do so again, they'll be timed out for 30 seconds, then a minute, then two, and so on. Every day, one violation for each member will be cleared.

Timeout Members Who Don't Yell In #yelling

---

uqcsbot/models.py
uqcsbot/yelling.py

Now editing messages in #yelling will result in a timeout if the message isn't yelled.

Timeout on edits in #yelling too.

---

uqcsbot/voteythumbs.py

Adds voteyrachels, voteytoms, voteyjimmys. Also adds some error checking.
Uses emoji that are already available.

Added voteyrachels, voteytoms, voteyjimmys

---

uqcsbot/holidays.py

Attempting to work out what is wrong with the holidays cog randomly failing. This adds logging for when the cog is run, so we can trace them on prod

Added logging for holidays cog

---

pyproject.toml
uqcsbot/error_handler.py
uqcsbot/member_counter.py
uqcsbot/uptime.py
uqcsbot/working_on.py

Fixed small typing issues in `error_handler`, `uptime` and `working_on`. All are very minor.

Fixed various typing issues

---

uqcsbot/__main__.py
uqcsbot/alfred.py

Adds a new command Alfred that provides useful information about flood warnings and UQ responses to Cyclone Alfred.
Thanks to @andrewj-brown for the idea

Adds Alfred
