- uqcsbot/jobs_bulletin.py
- uqcsbot/working_on.py
I suspect the "Users" ping perm is defaulting to the general setting of none; this *might* fix the problem of working-on pings going to random, unknown users
> Attempt at fixing working_on pings

- uqcsbot/advent.py
This restores the ID that was introduced as part of @TomCranitch's updated advent code but had a bad merge break it.
> Reintroducing advent ID after bad merge

- uqcsbot/yelling.py
Docstring was incorrect for function
Regex added to prevent links from being yelled at in the same method as the current method for ignoring emojis.
I'm not a regex pro so I stole the expression from: https://stackoverflow.com/questions/21932615/regular-expression-for-remove-link
> No more yelling at links (plus a little docstring fix)

- uqcsbot/advent.py
If the username is none then `.join` fails. In this case, the user is anonymous and we should display their user id
> Fix error when username is None

- .env.example
- uqcsbot/__main__.py
- uqcsbot/channels.py
- uqcsbot/models.py
- uqcsbot/starboard.py
uqcsbot now has a starboard!
For the uninitiated, a "starboard" is a channel where the bot can immortalise particularly funny messages from the server. The threshold for doing this is a certain number of reacts - messages with at least 5 "neat" reacts will be sent to the starboard.
Messages with at least 20 will be *pinned* in the starboard, the ultimate achievement in comedy.
Implementation details:
- the sent message accounts for 1 attached image, replies, and includes author, timestamp, and link to original
- all messages from admin categories `.startswith("admin")` are immune to starboarding
- messages that fall below thresholds are unpinned/deleted
- the content of the starboarded post is never edited, only the trimmings (i.e. number of reacts)
EDIT: following bikeshedding, the emoji …
> added starboard!

- uqcsbot/__main__.py
- uqcsbot/models.py
- uqcsbot/remindme.py
Adds a "remind me" functionality to the bot. The intended purpose is for committee to set "secondary" announcements in relevant channels (CAHP due dates in the tutor channel, CPG reminders in the cpg channel, etc.), though regular members may also set reminders. Members have a limit of 10 reminders (configurable in `remindme.py`), and mentions are disabled in reminder messages to prevent abuse. Admins override both of these restrictions.
A brief overview of the available commands, wrapped under the cog `RemindMe`:
- `/remindme add` adds a one-time reminder.
- `/remindme addrecurring` adds a recurring reminder.
- `/remindme remove` removes an existing reminder belonging to the user.
- `/remindme list` lists all active reminders belonging to the user.
> Add Reminders

- uqcsbot/whatweekisit.py
I thought this would be 2 lines, but it's actually 3. Please forgive me.
This makes the `/whatweekisit` command say today's date, rather than yesterday's, when run between the hours of 
00:00 and 10:00 (Brisbane time).
> Make whatweekisit timezone-aware

- uqcsbot/uptime.py
Uptime now finds #bot-testing by using a different channel ID depending on a Azure specific environment variable. This approach is the same as used in `bot.py`, so should have no issues. This should (hopefully) not affect production and provide reboot messages to the testing server.
> Modified uptime to also work in test server

- README.md
- tests/test_whatweekisit.py
A bit of a 2-part pull request, but both are quite small and related.
README now has a brief description of what is involved to write and run the (currently limited) tests of the bot. Feel free to adjust this as needed, as I'm not great at writing.
Corrected the `test_whatweeksiti.py` to pass. I didn't really change the test case, just read the given input file as unicode, as the non-breaking spaces for the empty table cells were being read as 2 non-space ASCII characters.
> Added description of testing to README and fixed test_whatweeksiti.py

- uqcsbot/text.py
Binify is currently limited to ASCII text. ASCII was a standard that originated in 1963, for use on old teleprinters. I think we can do better than that.
This patch extends the binify command to work with every character coding supported by python (a list of which can be found here: https://docs.python.org/3/library/codecs.html#standard-encodings). In addition, it sets the default character encoding to UTF-8, as it should be.
This patch also adds the hexify command, which does exactly the same thing as binify, but in hexadecimal.
> Support non-ASCII character encodings in binify

- uqcsbot/member_counter.py
`/membercount` did not work on the main server (despite working on the test server) due to permissions. Here are some error catching and logging mechanisms to allow easy checking of bot permissions and reasons for failure.
> Member count

- uqcsbot/latex.py
- uqcsbot/voteythumbs.py
- uqcsbot/xkcd.py
This PR should fix #101 somewhat.
However, some older commands should also be ported to the application-commands framework (`advent` (#68) and `holidays` come to mind), and subsequently deferred.
Also, this is my first OSS contribution, so I apologize if I've messed up in formatting / protocol for the PR.
> Defer voteythumbs request (also prettified latex, and deferred xkcd)

- tests/test_haiku.py
- uqcsbot/haiku.py
- uqcsbot/static/syllable_rules.yaml
Three (and a half) small bug fixes:
- The allowed channels list may not have loaded in time, so now a default empty list is provided.
- Words ending in "ye" now have consistent syllable checking rules. Fixes miscounts for words like "bayes" and "yes".
- Added an "ium" suffix to correctly count words like "gymnasium" and "chromium". Also added an exception for "belgium".
- Added "YT" as a acronym (as it contains a vowel-like letter it wasn't detected automatically).
> Haiku: Fixed small bugs with miscounting and allowed channels

- uqcsbot/cowsay.py
- uqcsbot/dominos_coupons.py
- uqcsbot/gaming.py
- uqcsbot/haiku.py
- uqcsbot/hoogle.py
- uqcsbot/latex.py
- uqcsbot/manage_cogs.py
- uqcsbot/minecraft.py
- uqcsbot/models.py
- uqcsbot/morse.py
- uqcsbot/past_exams.py
- uqcsbot/phonetics.py
- uqcsbot/text.py
- uqcsbot/voteythumbs.py
- uqcsbot/whatsdue.py
- uqcsbot/whatweekisit.py
- uqcsbot/yelling.py
The decorator `@yelling_exemptor()` applied to a command will now prevent that command from being used in `#yelling`. Argument can be given to the decorator, which will apply the minuscule filter to those command arguments e.g. `input_args=["message"]` will prevent the command from being used for a command that has `message` as an argument.
>  Create Decorator to Prevent Use of Commands With Minuscule Argument To Bot Commands In #yelling

- pyproject.toml
- uqcsbot/cog.py
- uqcsbot/yelling.py
The yelling exemptor breaks literally any command that uses `self`. This includes `bgg`, `cowsay`, `hoogle`, `manage_cogs`, `mcwhitelist`, `voteythumbs`, and `zalgo`.
This is the sort of issue that `pyright` *should* be able to pick up (and in fact, this PR currently shouldn't pass a typecheck, because every time you apply the yelling exemptor, it unthinkingly casts `commands.Cog` down to `UQCSBotCog`). The fact that it doesn't concerns me and I may have to investigate pyright configs to work out why this is the case.
> fix broken yelling exemptor

- uqcsbot/whatweekisit.py
Added random messages to make `/whatweekisit` more fun.
> Added Whatweekisit Flavour Text

- poetry.lock
- uqcsbot/manage_cogs.py
- uqcsbot/starboard.py
The default_permissions() decorator lets DMs through. This is cringe - we want to use default_permissions so that the server's role & moderation processes are abstracted out of the bot's code, and future committees can just fiddle with discord settings.
A more long-term solution is to have a decorator, `@requires_server` or the like, so we can continue to use default_permissions and just require that some commands must be used in the server. (This also would fix several other DM-based errors this PR identifies.) However, for now, let's just switch them all to `checks.has_permissions()` instead.
`grep -r permission` shows the following cogs use permissions:
- member_count: errors out on DMs anyway (should be fixed but who cares)
- minecraft: uses has_permissions() and Member-type-checks …
> fix permission checks on starboard interactions & manage_cogs

- uqcsbot/yelling.py
> fix yelling types and remove arbitrary web request

- uqcsbot/utils/advent_utils.py
The name provided by the AOC JSON is null if the user is anonymous. This is not corrected (and pyright doesn't pick up this error, as JSON is typed as `Dict[str, Any]`), so causes an error when displaying leaderboards of an anonymous user. this just make people have the name "Anon" if they don't have an AOC name.
> Fixed the bug crashing leaderboards from anonymous users

- uqcsbot/minecraft.py
New command for the new UQCS Minecraft Server. The command will "unwhitelist" the user while simultaneously kicking them from the server.
> Unwhitelist command

- uqcsbot/advent.py
As we disable the `allowed_mentions` on bot startup, messages that could ping people need to be explicitly defined. This patch adds these in to the advent cog.
> Add allowed_mentions to ping messages

- uqcsbot/minecraft.py
this causes a timeout (?) when whitelisting, sometimes. idk why.
It's pointless to have the exemptor on this command anyway, because capitalising a minecraft username will probably cause it to stop working.
> remove yelling exemptor from mcwhitelist

- uqcsbot/yelling.py
As I mentioned in https://github.com/UQComputingSociety/uqcsbot-discord/issues/198, one of the messages in the #yelling responses includes an (ironic) call for violence which may make some members uncomfortable and seems inappropriate for a club-sanctioned bot to be saying.
This pull request removes that message.
> Removed potentially inappropriate #yelling response

- uqcsbot/dominos_coupons.py
This gives the user the ability to choose between FrugalFeeds and Couponese through a source optional argument. I ended up making it so the bot's default behaviour is to give the user a randomly generated combined list of coupons. I changed the hyperlink for the embed to FrugalFeeds, as there's a more comprehensive collection of coupon codes there.
> Choose between FrugalFeeds and Couponese (issue #204)

- uqcsbot/utils/uq_course_utils.py
- uqcsbot/whatsdue.py
Recently (semester 2 2024) UQ has changed their ECP management from [ECPS](https://systems-training.its.uq.edu.au/ecps) to [JAC](https://systems-training.its.uq.edu.au/jac). This means that many of the ECP related functions stopped working (as they were based off [a old service started in 2006](https://www.courses.uq.edu.au/student_section_report.php?report=assessment&profileIds=133473)).
This PR rewrites most of these to work with the new system, letting `whatsdue` work again. There are some slight stylistic changes made to the output, due to certain links no longer being available, and the due dates for many courses actually being descriptions. ECPs from before sem 2 2024 will no longer be able to be processed, as these should no longer be needed.
There might also be some future …
> Whatsdue: fixed to work with the new JAC system

- uqcsbot/utils/snailrace_utils.py
This adds short messages with the winner announcement when a snail race is completed. There are three categories: proper winner, tie, and no contest. A no contest result occurs when only a single snail competes in a race. This PR resolves #118, and as such it pokes fun at single snail races.
I decided to make winner announcements quite short and simple, and tie announcements messages exciting and potentially call for a rematch.
Feel free to let me know if there are any messages you think should be included or you don't feel should be included.
> Add fun messages on race conclusion (Issue #118)

- uqcsbot/advent.py
- uqcsbot/models.py
This consists of two parts (that could have been separate PRs but are related).
Firstly, better error are now given session token expires. If the session token expires, the leaderboard page redirects to the advent home page (with a successful 200 response code) so the bot fails to read this as python. If we block redirects, we can detect this earlier and provide a better error message.
Secondly, AOC registrations did not persist between years. By removing the year in the registrations table, registrations will persist between years. Not that this will also require access to the database to remove this column. PLEASE DON'T MERGE until this is done. Once reviewed, I am happy to do this.
> Adjustments to Advent of Code

- uqcsbot/advent.py
- uqcsbot/utils/advent_utils.py
optimisation to cache image data when switching to/from full view. this is done by lru_cache, currently with a size of 16 (enough for 8 /leaderboard calls, with 2 image each)
> advent: increase interaction timeout and optimise

- uqcsbot/advent.py
The AoC [automation guidelines](https://old.reddit.com/r/adventofcode/wiki/faqs/automation) specify that we should have a user-agent header on outgoing requests, so here is one.
> advent: Add user-agent header to leaderboard requests

- uqcsbot/__main__.py
Currently, the minecraft cog is loaded every time the bot restarts, despite the Minecraft server not being a thing for years. This single character change will prevent it from being loaded on restarts. The cog can still be loaded and unloaded using the `/managecogs action:load cog:minecraft` command. If a new Minecraft server is created in the future, I encourage whoever is responsible to remove the offending `#`.
> Do not load minecraft cog
